In [2]:
import numpy as np
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
#Get Dimension
print(f'a dimensions: {a.ndim}')
print(f'b dimensions: {b.ndim}')

a dimensions: 1
b dimensions: 2


In [9]:
# Get Shape
print(f'a shape: {a.shape}')
print(f'b shape: {b.shape}')

a shape: (3,)
b shape: (2, 3)


In [10]:
# Get Type
print(f'a type: {a.dtype}')
print(f'b type: {b.dtype}')

a type: int32
b type: float64


In [14]:
# Get Size
print(f'a item size: {a.itemsize}')
print(f'b item size: {b.itemsize}')

a item size: 4
b item size: 8


In [12]:
# Get Total Size
print(f'a total size: {a.nbytes}')
print(f'b total size: {b.nbytes}')

a total size: 12
b total size: 48


In [13]:
# Get number of elements
print(f'a number of elements: {a.size}')
print(f'b number of elements: {b.size}')

a number of elements: 3
b number of elements: 6


In [15]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
# Get specific element
a[1,5]

np.int64(13)

In [17]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [19]:
# Splicing [start:end:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [20]:
#assignment
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [21]:
# 3d array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
# Get specific element in 3d
c[0][1][1] 
#or 
c[0,1,1]

np.int64(4)

In [25]:
# during assignment the value should be of same shape
c[:,1,:] = [[9,9],[8,8]]

In [26]:
c

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [27]:
# 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# 1's matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [30]:
# n's matrix
n=np.full((2,2),99)
print(n)
print(n.dtype)

[[99 99]
 [99 99]]
int64


In [31]:
# n's matrix using full_like, first parameter takes in
# an np array for size and the other parameter for value
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [33]:
# Random value
np.random.rand(4,3)

array([[0.03911239, 0.49450141, 0.46377362],
       [0.30008849, 0.27382386, 0.18833137],
       [0.43485408, 0.54833429, 0.37356394],
       [0.83732241, 0.40228148, 0.70651131]])

In [34]:
np.random.randint(-4,8, size=(3,3))

array([[-1,  5, -3],
       [-4,  1, -3],
       [ 3,  6,  2]], dtype=int32)

In [35]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:

arr = np.array([[1,2,3]])
# Repeat the array 3 times
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [37]:
# slicing and insertion in another array

output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
# Copying an array to another array copies the values
a = np.array([1,2,3])
print(a)
b = a.copy()
print(b)

b[0] = 100
print(b)
print(a)

# Direct assignment copies the reference
c=a
c[0] = 90
print(c)
print(a)


[1 2 3]
[1 2 3]
[100   2   3]
[1 2 3]
[90  2  3]
[90  2  3]


In [40]:
a = np.array([1,2,3,4])
# adds the value 2 to all elements
a+2

array([3, 4, 5, 6])

In [41]:
# subtracts the value 2 from all elements
a - 2 

array([-1,  0,  1,  2])

In [42]:
a * 2

array([2, 4, 6, 8])

In [43]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [44]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [45]:
a**2

array([ 1,  4,  9, 16])

In [46]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [47]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [48]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
# matrix multiplication
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [49]:
c = np.identity(3)
# calculate determinate
np.linalg.det(c)

np.float64(1.0)

In [50]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.min(stats)

np.int64(1)

In [52]:
np.max(stats, axis=1)

array([3, 6])

In [53]:
np.max(stats, axis=0)

array([4, 5, 6])

In [58]:
# Reorganising Arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# Do note that the shape should be a multiple of the number of elements
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [59]:
# vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])